### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by jhgorse** [okanbulut/bigdata#1]
Chapter 5, Visualizing big data appears to have a link to a hijacked domain (NSFW, it forwards to a Russian adult content website): http://www.ggplot2-exts.org/gallery/

The new domain appears to be:
https://exts.ggplot2.tidyverse.org/gallery/

Cheers,
Joe

**Comment by okanbulut** [comment]
Thank you for letting us know, Joe. We'll update the link.

Okan

**Comment by okanbulut** [comment]
The links have been fixed.
